name: StoreCheck
on:
    push:
        branches:
            - master
        tags:
            - '*'

env:
    PLUGIN_NAME: ${{ github.event.repository.name }}
    ACCOUNT_USER: ${{ secrets.ACCOUNT_USER }}
    ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
    PLUGIN_UPLOADER_VERSION: 0.3.11

jobs:
    validatePlugin:
        if: startsWith(github.ref, 'refs/tags/') != true
        name: Check for Store compliance
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: getPluginUploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/${{ env.PLUGIN_UPLOADER_VERSION }}/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: Build Zip
                run: php frosh-plugin-upload.phar ext:zip ${PLUGIN_NAME}

            -   name: Validate Zip
                run: php frosh-plugin-upload.phar ext:validate $(pwd)/${PLUGIN_NAME}*.zip

    StoreUpdate:
        needs: validatePlugin
        name: Update Store page
        if: startsWith(github.ref, 'refs/tags/') != true
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: getPluginUploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/${{ env.PLUGIN_UPLOADER_VERSION }}/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: StoreUpdate
                run: php frosh-plugin-upload.phar ext:update $(pwd)/${{ env.PLUGIN_NAME }}/

    StoreRelease:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        name: Upload Extension to Store
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: Download Extension Uploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/${{ env.PLUGIN_UPLOADER_VERSION }}/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: Build Zip
                run: php frosh-plugin-upload.phar ext:zip ${PLUGIN_NAME}

            -   name: StoreUpload
                run: php frosh-plugin-upload.phar ext:upload $(pwd)/${PLUGIN_NAME}*.zip --createRelease
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
